global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs: 
      - targets: ['localhost:9090']

  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['172.17.0.1:9323'] 

  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['172.17.0.1:8080']

  # - job_name: 'spring-boot-app'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['172.17.0.1:8081']
